<a href="https://colab.research.google.com/github/Tarikol-Islam/Crops_Price_Prediction_Linear_Regrssion/blob/main/Crops_Price_Prediction_Linear_Regrssion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
uploaded = files.upload()

Saving Dataset_Rice_Dataset.csv to Dataset_Rice_Dataset.csv


In [64]:
DataFrame = pd.read_csv('Dataset_Rice_Dataset.csv')
DataFrame


Crops  Year       Region  ...  Rainfall(m)  Fertilizer(M.Ton)       Price
0    Rice  2016    Bandarban  ...        3.989            1181.45   227342240
1    Rice  2016   Chattagram  ...        9.981           18374.76  3585670640
2    Rice  2016  Cox's Bazar  ...        6.770           14011.02  2802680090
3    Rice  2016      Cumilla  ...        5.793           44689.70  9473875950
4    Rice  2016     Chandpur  ...        7.538           17907.77  3562696160
..    ...   ...          ...  ...          ...                ...         ...
129     0     0            0  ...        0.000              34.00           0
130     0     0            0  ...        0.000              65.00           0
131     0     0            0  ...        0.000              54.00           0
132     0     0            0  ...        0.000               0.00           0
133     0     0            0  ...        0.000               0.00           0

[134 rows x 9 columns]

In [69]:
Regression = linear_model.LinearRegression()
Regression.fit(DataFrame[['Area(Acres)','Rainfall(m)','Rate(Ton/Acre)','Fertilizer(M.Ton)']],DataFrame[['Production(M.Ton)']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [56]:
Regression.coef_, Regression.intercept_, Regression.singular_

(array([[  175.40134454, 23599.86324713, -1358.78314464]]),
 array([76270.51981232]),
 array([2.62851441e+06, 1.06232254e+02, 2.17097727e+01]))

In [71]:

Prediction = Regression.predict([[float(input("Enter Area: ")),float(input("Enter Rainfall: ")), DataFrame['Rate(Ton/Acre)'].mean(),float(input("Enter Fertilizer: "))]])
Prediction


Enter Area: 0
Enter Rainfall: 5
Enter Fertilizer: 0


array([[189406.97515333]])